---
# Project information
site_name: Rocky Linux Wiki
site_url: https://wiki.rockylinux.org
site_description: >-
  Rocky Linux project wiki

# Repository
repo_url: https://github.com/rocky-linux/wiki.rockylinux.org
repo_name: rocky-linux/wiki.rockylinux.org
edit_uri: edit/development/docs/

# Copyright
copyright: Copyright &copy; 2026 Rocky Enterprise Software Foundation

# Configuration
theme:
  variant: classic
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - perl
    - python
    - yaml
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.action.edit
  logo: assets/icon-white.svg

# Plugins
plugins:
  - autolinks
  - awesome-nav
  - git-revision-date-localized
  - macros:
      include_dir: docs/include
  - redirects:
      redirect_maps:
        'team/release_engineering/packagekit.md': 'rocky/packagekit.md'
        'team/release_engineering/debranding/index.md': 'https://sig-core.rocky.page/documentation/debranding'
        'team/release_engineering/compose/index.md': 'https://sig-core.rocky.page/sop/'
        'team/release_engineering/guidelines/rocky_logos_guidelines/index.md': 'https://sig-core.rocky.page/documentation/guidelines/rocky_logos_guidelines/'
        'team/testing/index.md': 'https://testing.rocky.page/'
        'team/testing/qa_test_cases/index.md': 'https://testing.rocky.page/documentation/qa_test_cases'
        'team/testing/release_criteria/release_criteria/index.md': 'https://testing.rocky.page/guidelines/release_criteria/release_criteria/'
        'team/testing/release_criteria/r8/8_release_criteria/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r8/8_release_criteria/'
        'team/testing/release_criteria/r8/8.6_qa_testing_summary/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r8/8.6_qa_testing_summary/'
        'team/testing/release_criteria/r8/8.6_qa_testing_go_no_go/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r8/8.6_qa_testing_go_no_go/'
        'team/testing/release_criteria/r9/9_release_criteria/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r9/9_release_criteria/'
        'team/testing/release_criteria/r9/9.0_qa_testing_summary/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r9/9.0_qa_testing_summary/'
        'team/testing/release_criteria/r9/9.0_qa_testing_go_no_go/index.md': 'https://testing.rocky.page/guidelines/release_criteria/r9/9.0_qa_testing_go_no_go/'
        'team/testing/dev_guides/wiki_development_boxes/index.md': 'https://testing.rocky.page/documentation/dev_guides/wiki_development_boxes/'
        'team/testing/dev_guides/commit_signing/index.md': 'https://testing.rocky.page/documentation/dev_guides/commit_signing/'
        'team/testing/dev_guides/openqa_access/index.md': 'https://testing.rocky.page/documentation/dev_guides/openqa_access/'
        'team/testing/dev_guides/openqa_cli_post_examples/index.md': 'https://testing.rocky.page/documentation/dev_guides/openqa_cli_post_examples/'
        'team/testing/dev_guides/openqa_clone_job_examples/index.md': 'https://testing.rocky.page/documentation/dev_guides/openqa_clone_job_examples/'
        'team/testing/dev_guides/openqa_clone_custom_git_refspec_examples/index.md': 'https://testing.rocky.page/documentation/dev_guides/openqa_clone_custom_git_refspec_examples/'
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
